author: "Yiming Chen"
time_format: "%B %d, %Y"
article_format: ".html.md"

symbols:
  __1__: "!"
  __2__: "@"
  __3__: "#"
  __4__: "$"
  __5__: "%"
  __6__: "^"
  __7__: "&"
  __8__: "*"
  __9__: "("
  __0__: ")"
  __mi__: "-"
  __pl__: "+"
  __eq__: "="
  __ob__: "["
  __cb__: "]"
  __ocb__: "{"
  __ccb__: "}"
  __bar__: "|"
  __col__: ":"
  __scol__: ";"
  __quo__: "'"
  __dquo__: "\""
  __com__: ","
  __dot__: "."
  __lt__: "<"
  __gt__: ">"
  __sl__: "/"
  __bsl__: "\\"
  __qst__: "?"
